spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-mute-term-aia4bqoq-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_GuR21CbhFfPx

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
